-- Seed site_content table
INSERT INTO site_content (key, value_en, value_ar, section, updated_at) VALUES
('hero_title', 'UAE Tax & Accounting Solutions', 'حلول الضرائب والمحاسبة في الإمارات', 'hero', NOW()),
('hero_subtitle', 'Expert guidance for corporate tax, VAT compliance, and financial advisory services', 'إرشادات خبيرة للضرائب على الشركات والامتثال لضريبة القيمة المضافة والخدمات الاستشارية المالية', 'hero', NOW()),
('hero_cta', 'Get Expert Consultation', 'احصل على استشارة خبيرة', 'hero', NOW()),
('about_mission', 'To provide comprehensive tax and accounting solutions that empower UAE businesses to achieve sustainable growth and regulatory compliance', 'تقديم حلول ضرائب ومحاسبة شاملة تمكن الشركات الإماراتية من تحقيق النمو المستدام والامتثال التنظيمي', 'about', NOW()),
('about_vision', 'To be the most trusted tax advisory partner for UAE businesses, known for expertise, innovation, and client success', 'أن نكون شريك الاستشارات الضريبية الأكثر ثقة للشركات الإماراتية، معروفون بالخبرة والابتكار ونجاح العملاء', 'about', NOW()),
('about_description', 'Sage Advisory is a leading UAE-based tax and accounting firm dedicated to helping businesses navigate complex tax regulations, optimize financial operations, and achieve their growth objectives. With 12 years of industry experience and a team of qualified professionals, we deliver tailored solutions for startups, SMEs, and large corporations.', 'تعد Sage Advisory شركة استشارات ضرائب ومحاسبة رائدة مقرها الإمارات وتكرس جهودها لمساعدة الشركات على التنقل في لوائح الضرائب المعقدة وتحسين العمليات المالية وتحقيق أهدافها النمائية. مع 12 سنة من خبرة الصناعة وفريق من المتخصصين المؤهلين، نقدم حلولاً مخصصة للشركات الناشئة والشركات الصغيرة والمتوسطة والشركات الكبرى.', 'about', NOW()),
('counter_clients', '950', '950', 'counters', NOW()),
('counter_saved', '120', '120', 'counters', NOW()),
('counter_industries', '35', '35', 'counters', NOW()),
('counter_years', '12', '12', 'counters', NOW()),
('contact_phone', '+971 58 570 4140', '+971 58 570 4140', 'contact', NOW()),
('contact_email', 'info@sageadvisory.ae', 'info@sageadvisory.ae', 'contact', NOW()),
('contact_location', 'Dubai, U.A.E', 'دبي، الإمارات العربية المتحدة', 'contact', NOW()),
('footer_tagline', 'Your trusted partner for tax compliance and financial excellence in the UAE', 'شريكك الموثوق لالتزام الضرائب والتميز المالي في الإمارات', 'footer', NOW());

-- Seed services table - Tax Category
INSERT INTO services (slug, category, name_en, name_ar, description_en, description_ar, long_description_en, long_description_ar, features, flow_steps, documents, faqs, icon, sort_order, is_active, created_at, updated_at) VALUES

-- VAT Service
('vat', 'tax',
'VAT Registration & Compliance',
'تسجيل ضريبة القيمة المضافة والامتثال',
'Complete VAT registration and compliance services tailored to your business needs',
'خدمات تسجيل ضريبة القيمة المضافة والامتثال الكاملة المخصصة لاحتياجات عملك',
'Our VAT experts help businesses register with FTA, manage monthly/quarterly filings, optimize input VAT recovery, and ensure continuous compliance. We handle all aspects of VAT management from registration to audit preparation, ensuring your business remains compliant while maximizing tax efficiency.',
'يساعد خبراؤنا في ضريبة القيمة المضافة الشركات على التسجيل لدى FTA وإدارة الإقرارات الشهرية والربع سنوية وتحسين استرجاع ضريبة المدخلات والامتثال المستمر. نتعامل مع جميع جوانب إدارة ضريبة القيمة المضافة من التسجيل إلى تحضير التدقيق، مما يضمن بقاء عملك متوافقاً مع الكفاءة الضريبية القصوى.',
'[{"title_en":"Expert FTA Registration","title_ar":"تسجيل FTA الخبير","description_en":"Seamless registration with Federal Tax Authority","description_ar":"تسجيل سلس لدى سلطة الضرائب الفيدرالية"},{"title_en":"Monthly/Quarterly Filings","title_ar":"الإقرارات الشهرية والربع سنوية","description_en":"Timely and accurate tax return submissions","description_ar":"تقديم إقرارات ضريبية دقيقة وفي الوقت المناسب"},{"title_en":"Input VAT Recovery","title_ar":"استرجاع ضريبة المدخلات","description_en":"Maximize legitimate tax credits","description_ar":"تحقيق أقصى استفادة من الأرصدة الضريبية المشروعة"},{"title_en":"Audit Support","title_ar":"دعم التدقيق","description_en":"Comprehensive audit preparation and representation","description_ar":"تحضير شامل للتدقيق والتمثيل"}]',
'[{"step":1,"title_en":"Business Assessment","title_ar":"تقييم الأعمال","description_en":"Evaluate VAT obligation based on turnover","description_ar":"تقييم التزام ضريبة القيمة المضافة بناءً على الإيرادات"},{"step":2,"title_en":"Registration Application","title_ar":"طلب التسجيل","description_en":"Submit FTA registration forms and documentation","description_ar":"تقديم نماذج التسجيل والوثائق"},{"step":3,"title_en":"System Setup","title_ar":"إعداد النظام","description_en":"Configure accounting systems for VAT tracking","description_ar":"تكوين الأنظمة المحاسبية لتتبع ضريبة القيمة المضافة"},{"step":4,"title_en":"Monthly Compliance","title_ar":"الامتثال الشهري","description_en":"Ongoing returns and compliance management","description_ar":"إدارة الإقرارات المستمرة والامتثال"}]',
'[{"name":"VAT Application Forms","name_ar":"نماذج التطبيق"},{"name":"Business License","name_ar":"رخصة العمل"},{"name":"Financial Statements","name_ar":"البيانات المالية"}]',
'[{"question_en":"What is the VAT threshold in UAE?","question_ar":"ما هو حد ضريبة القيمة المضافة في الإمارات؟","answer_en":"Businesses with annual turnover exceeding AED 375,000 must register for VAT","answer_ar":"يجب على الشركات التي يتجاوز دخلها السنوي 375 ألف درهم التسجيل لضريبة القيمة المضافة"},{"question_en":"How often should VAT returns be filed?","question_ar":"كم مرة يجب تقديم إقرارات ضريبة القيمة المضافة؟","answer_en":"Monthly or quarterly depending on your annual turnover and election","answer_ar":"شهري أو ربع سنوي حسب دخلك السنوي والخيار المختار"}]',
'receipt',
1, TRUE, NOW(), NOW()),

-- Corporate Tax Service
('corporate-tax', 'tax',
'Corporate Income Tax',
'ضريبة دخل الشركات',
'Strategic corporate tax planning and compliance for UAE businesses',
'تخطيط ضريبة دخل الشركات الاستراتيجي والامتثال للشركات الإماراتية',
'Navigate UAE corporate tax requirements with confidence. Our team provides strategic tax planning, helps optimize your tax position, prepares annual corporate tax returns, and ensures compliance with all FTA requirements. We work with your financial team to identify tax-efficient structures and opportunities.',
'تنقل متطلبات ضريبة دخل الشركات الإماراتية بثقة. يقدم فريقنا تخطيط ضريبي استراتيجي ويساعد في تحسين موقفك الضريبي وتحضير إقرارات ضريبة دخل الشركات السنوية والامتثال لجميع متطلبات FTA. نعمل مع فريقك المالي لتحديد الهياكل الفعالة من حيث الضرائب والفرص.',
'[{"title_en":"Tax Planning","title_ar":"التخطيط الضريبي","description_en":"Strategic optimization of tax position","description_ar":"التحسين الاستراتيجي للموقف الضريبي"},{"title_en":"Return Preparation","title_ar":"تحضير الإقرار","description_en":"Accurate annual corporate tax returns","description_ar":"إقرارات ضريبة دخل الشركات السنوية الدقيقة"},{"title_en":"Compliance","title_ar":"الامتثال","description_en":"Full FTA compliance and documentation","description_ar":"الامتثال الكامل لـ FTA والتوثيق"},{"title_en":"Appeals","title_ar":"الاستئنافات","description_en":"Tax dispute resolution and representation","description_ar":"حل نزاعات الضرائب والتمثيل"}]',
'[{"step":1,"title_en":"Financial Review","title_ar":"مراجعة مالية","description_en":"Comprehensive analysis of financial statements","description_ar":"تحليل شامل للبيانات المالية"},{"step":2,"title_en":"Tax Position Analysis","title_ar":"تحليل الموقف الضريبي","description_en":"Identify tax risks and opportunities","description_ar":"تحديد مخاطر الضرائب والفرص"},{"step":3,"title_en":"Return Preparation","title_ar":"تحضير الإقرار","description_en":"Prepare and file corporate tax return","description_ar":"تحضير وتقديم إقرار ضريبة الشركات"},{"step":4,"title_en":"Documentation","title_ar":"التوثيق","description_en":"Maintain compliance records and documentation","description_ar":"الحفاظ على سجلات الامتثال والتوثيق"}]',
'[{"name":"Financial Statements","name_ar":"البيانات المالية"},{"name":"Trial Balance","name_ar":"ميزان المراجعة"},{"name":"Supporting Documentation","name_ar":"الوثائق الداعمة"}]',
'[{"question_en":"What is the corporate tax rate in UAE?","question_ar":"ما هو معدل ضريبة دخل الشركات في الإمارات؟","answer_en":"UAE has a 0% corporate tax rate for most businesses, except for certain sectors like oil & gas","answer_ar":"الإمارات لديها معدل ضريبة دخل شركات بنسبة 0% لمعظم الشركات، باستثناء قطاعات معينة مثل النفط والغاز"},{"question_en":"When is the corporate tax return due?","question_ar":"متى يستحق تقديم إقرار ضريبة دخل الشركات؟","answer_en":"Returns are typically due 90 days after the end of the tax year","answer_ar":"عادة ما تكون الإقرارات مستحقة في غضون 90 يوماً بعد نهاية السنة الضريبية"}]',
'briefcase',
2, TRUE, NOW(), NOW()),

-- Excise Tax Service
('excise-tax', 'tax',
'Excise Tax Management',
'إدارة ضريبة الاستهلاك',
'Excise tax compliance and management for regulated industries',
'امتثال إدارة ضريبة الاستهلاك للصناعات المنظمة',
'If your business handles excisable goods (tobacco, energy drinks, carbonated beverages, etc.), our experts ensure proper excise tax registration, calculation, and timely compliance filings. We help you understand excise obligations and implement compliant operational procedures.',
'إذا كان عملك يتعامل مع السلع الخاضعة للاستهلاك (التبغ والمشروبات الطاقية والمشروبات الغازية وغيرها)، يضمن خبراؤنا التسجيل الصحيح لضريبة الاستهلاك والحساب والامتثال لتقديم الإقرارات في الوقت المناسب. نساعدك على فهم التزامات الاستهلاك وتنفيذ إجراءات تشغيلية متوافقة.',
'[{"title_en":"Excise Registration","title_ar":"تسجيل الاستهلاك","description_en":"Register with authorities for excisable goods","description_ar":"التسجيل مع السلطات للسلع الخاضعة للاستهلاك"},{"title_en":"Tax Calculation","title_ar":"حساب الضريبة","description_en":"Accurate excise tax rate application","description_ar":"تطبيق معدل ضريبة الاستهلاك الدقيق"},{"title_en":"Quarterly Filings","title_ar":"الإقرارات ربع السنوية","description_en":"Timely excise tax return submissions","description_ar":"تقديم إقرارات ضريبة الاستهلاك في الوقت المناسب"},{"title_en":"Audit Support","title_ar":"دعم التدقيق","description_en":"Defense in excise tax audits","description_ar":"الدفاع في تدقيق ضريبة الاستهلاك"}]',
'[{"step":1,"title_en":"Business Assessment","title_ar":"تقييم الأعمال","description_en":"Identify excisable products in your portfolio","description_ar":"تحديد المنتجات الخاضعة للاستهلاك في محفظتك"},{"step":2,"title_en":"Registration","title_ar":"التسجيل","description_en":"Register as excise taxpayer with FTA","description_ar":"التسجيل كدافع ضريبة استهلاك مع FTA"},{"step":3,"title_en":"System Setup","title_ar":"إعداد النظام","description_en":"Configure tracking and reporting systems","description_ar":"تكوين أنظمة التتبع والإبلاغ"},{"step":4,"title_en":"Ongoing Compliance","title_ar":"الامتثال المستمر","description_en":"Manage quarterly returns and audits","description_ar":"إدارة الإقرارات ربع السنوية والتدقيق"}]',
'[{"name":"Product Inventory","name_ar":"قائمة جرد المنتجات"},{"name":"Sales Records","name_ar":"سجلات المبيعات"},{"name":"Tax Calculations","name_ar":"حسابات الضرائب"}]',
'[{"question_en":"Which products are subject to excise tax?","question_ar":"ما هي المنتجات الخاضعة لضريبة الاستهلاك؟","answer_en":"Tobacco, energy drinks, carbonated beverages, and certain electronic products are subject to excise tax","answer_ar":"التبغ والمشروبات الطاقية والمشروبات الغازية والمنتجات الإلكترونية معينة تخضع لضريبة الاستهلاك"}]',
'percentage',
3, TRUE, NOW(), NOW());

-- Accounting Services - Accounting Category
INSERT INTO services (slug, category, name_en, name_ar, description_en, description_ar, long_description_en, long_description_ar, features, flow_steps, documents, faqs, icon, sort_order, is_active, created_at, updated_at) VALUES

('accounting-services', 'accounting',
'Full Accounting Services',
'خدمات المحاسبة الكاملة',
'Comprehensive bookkeeping and accounting solutions for all business sizes',
'حلول محاسبة وتسجيل دفاتر شاملة لجميع أحجام الأعمال',
'From daily bookkeeping to annual financial statements, our accounting team handles all aspects of financial record-keeping. We use modern accounting software, maintain compliance with UAE accounting standards, prepare monthly management accounts, and ensure your financial records are accurate and audit-ready.',
'من التسجيل اليومي إلى البيانات المالية السنوية، يتعامل فريق محاسباتنا مع جميع جوانب الحفاظ على السجلات المالية. نستخدم برامج محاسبية حديثة، والامتثال للمعايير المحاسبية الإماراتية، وتحضير حسابات الإدارة الشهرية، والتأكد من دقة سجلاتك المالية وجاهزيتها للتدقيق.',
'[{"title_en":"Daily Bookkeeping","title_ar":"التسجيل اليومي","description_en":"Recording all transactions and entries","description_ar":"تسجيل جميع المعاملات والقيود"},{"title_en":"Month-End Close","title_ar":"إغلاق نهاية الشهر","description_en":"Monthly reconciliation and closing procedures","description_ar":"المصالحة الشهرية وإجراءات الإغلاق"},{"title_en":"Financial Reporting","title_ar":"التقارير المالية","description_en":"Management accounts and financial statements","description_ar":"حسابات الإدارة والبيانات المالية"},{"title_en":"Payroll Processing","title_ar":"معالجة الرواتب","description_en":"Employee payroll and government compliance","description_ar":"رواتب الموظفين والامتثال الحكومي"}]',
'[{"step":1,"title_en":"Initial Setup","title_ar":"الإعداد الأولي","description_en":"Configure accounting systems and chart of accounts","description_ar":"تكوين الأنظمة المحاسبية وخطة الحسابات"},{"step":2,"title_en":"Transaction Processing","title_ar":"معالجة المعاملات","description_en":"Daily recording of invoices, payments, and receipts","description_ar":"التسجيل اليومي للفواتير والدفعات والإيصالات"},{"step":3,"title_en":"Bank Reconciliation","title_ar":"مصالحة البنك","description_en":"Regular bank account reconciliation","description_ar":"مصالحة حسابات البنك بانتظام"},{"step":4,"title_en":"Financial Statements","title_ar":"البيانات المالية","description_en":"Prepare monthly P&L and balance sheet","description_ar":"تحضير بيان الدخل والميزانية العمومية الشهرية"}]',
'[{"name":"Bank Statements","name_ar":"كشوف الحسابات البنكية"},{"name":"Invoices","name_ar":"الفواتير"},{"name":"Expense Receipts","name_ar":"إيصالات النفقات"},{"name":"Payroll Records","name_ar":"سجلات الرواتب"}]',
'[{"question_en":"How often should accounting records be updated?","question_ar":"كم مرة يجب تحديث السجلات المحاسبية؟","answer_en":"Transactions should be recorded daily for accurate financial management","answer_ar":"يجب تسجيل المعاملات يومياً للإدارة المالية الدقيقة"},{"question_en":"What accounting standards apply in UAE?","question_ar":"ما هي معايير المحاسبة المعمول بها في الإمارات؟","answer_en":"UAE companies must follow IFRS (International Financial Reporting Standards)","answer_ar":"يجب على شركات الإمارات اتباع IFRS (معايير الإبلاغ المالي الدولية)"}]',
'calculator',
4, TRUE, NOW(), NOW()),

('bookkeeping-services', 'accounting',
'Professional Bookkeeping',
'التسجيل الاحترافي',
'Accurate and timely bookkeeping for your business',
'التسجيل الدقيق والفي الوقت المناسب لعملك',
'Keep your financial records clean and compliant with our professional bookkeeping services. Whether you need part-time bookkeeper support or full-service accounting, we ensure every transaction is properly recorded, categorized, and reconciled.',
'احتفظ بسجلاتك المالية نظيفة ومتوافقة مع خدمات التسجيل الاحترافية لدينا. سواء كنت بحاجة إلى دعم محاسب بدوام جزئي أو خدمات محاسبية كاملة، فإننا نضمن تسجيل كل معاملة بشكل صحيح وتصنيفها ومصالحتها.',
'[{"title_en":"Daily Entry Recording","title_ar":"تسجيل القيود اليومية","description_en":"All transactions recorded accurately","description_ar":"تسجيل جميع المعاملات بدقة"},{"title_en":"Bank Reconciliation","title_ar":"مصالحة البنك","description_en":"Monthly bank account matching","description_ar":"مطابقة حساب البنك الشهرية"},{"title_en":"Invoice Management","title_ar":"إدارة الفواتير","description_en":"Receivables and payables tracking","description_ar":"تتبع الذمم المدينة والدائنة"},{"title_en":"Trial Balance","title_ar":"ميزان المراجعة","description_en":"Monthly account verification","description_ar":"التحقق من الحساب الشهري"}]',
'[{"step":1,"title_en":"Account Setup","title_ar":"إعداد الحساب","description_en":"Configure chart of accounts","description_ar":"تكوين خطة الحسابات"},{"step":2,"title_en":"Data Entry","title_ar":"إدخال البيانات","description_en":"Record daily transactions","description_ar":"تسجيل المعاملات اليومية"},{"step":3,"title_en":"Verification","title_ar":"التحقق","description_en":"Review and verify entries","description_ar":"مراجعة والتحقق من القيود"},{"step":4,"title_en":"Reporting","title_ar":"الإبلاغ","description_en":"Generate monthly reports","description_ar":"إنشاء التقارير الشهرية"}]',
'[{"name":"Transaction Records","name_ar":"سجلات المعاملات"},{"name":"Bank Statements","name_ar":"كشوف الحسابات البنكية"},{"name":"Receipts and Invoices","name_ar":"الإيصالات والفواتير"}]',
'[{"question_en":"Can you handle multiple currencies?","question_ar":"هل يمكنك التعامل مع عملات متعددة؟","answer_en":"Yes, we manage transactions in AED, USD, and other currencies with proper FX treatment","answer_ar":"نعم، نتعامل مع المعاملات بالدرهم والدولار والعملات الأخرى مع معاملة الصرف الأجنبي الصحيحة"}]',
'document',
5, TRUE, NOW(), NOW()),

('internal-auditing', 'accounting',
'Internal Audit Services',
'خدمات التدقيق الداخلي',
'Strengthen controls and operations with internal audit',
'تقوية الضوابط والعمليات مع التدقيق الداخلي',
'Our internal audit specialists help identify risks, evaluate internal controls, and improve operational efficiency. We conduct comprehensive internal audits that provide management with actionable insights to strengthen your organization.',
'يساعد متخصصو التدقيق الداخلي لدينا على تحديد المخاطر وتقييم الضوابط الداخلية وتحسين الكفاءة التشغيلية. نجري تدقيق داخلي شامل يزود الإدارة برؤى قابلة للتنفيذ لتقوية مؤسستك.',
'[{"title_en":"Risk Assessment","title_ar":"تقييم المخاطر","description_en":"Identify operational and financial risks","description_ar":"تحديد مخاطر تشغيلية ومالية"},{"title_en":"Control Testing","title_ar":"اختبار الضوابط","description_en":"Evaluate effectiveness of controls","description_ar":"تقييم فعالية الضوابط"},{"title_en":"Audit Report","title_ar":"تقرير التدقيق","description_en":"Detailed findings and recommendations","description_ar":"النتائج والتوصيات التفصيلية"},{"title_en":"Follow-up","title_ar":"المتابعة","description_en":"Track implementation of recommendations","description_ar":"تتبع تنفيذ التوصيات"}]',
'[{"step":1,"title_en":"Audit Planning","title_ar":"تخطيط التدقيق","description_en":"Define scope and objectives","description_ar":"تحديد النطاق والأهداف"},{"step":2,"title_en":"Fieldwork","title_ar":"العمل الميداني","description_en":"Execute audit procedures","description_ar":"تنفيذ إجراءات التدقيق"},{"step":3,"title_en":"Analysis","title_ar":"التحليل","description_en":"Analyze findings and control gaps","description_ar":"تحليل النتائج والفجوات في الضوابط"},{"step":4,"title_en":"Reporting","title_ar":"الإبلاغ","description_en":"Issue audit report with recommendations","description_ar":"إصدار تقرير التدقيق مع التوصيات"}]',
'[{"name":"Audit Plan","name_ar":"خطة التدقيق"},{"name":"Internal Controls Documentation","name_ar":"توثيق الضوابط الداخلية"},{"name":"Process Documentation","name_ar":"توثيق العملية"}]',
'[{"question_en":"What is the difference between internal and external audit?","question_ar":"ما الفرق بين التدقيق الداخلي والخارجي؟","answer_en":"Internal audit focuses on improving operations and controls; external audit verifies financial statement accuracy","answer_ar":"يركز التدقيق الداخلي على تحسين العمليات والضوابط؛ يتحقق التدقيق الخارجي من دقة البيانات المالية"}]',
'shield',
6, TRUE, NOW(), NOW()),

('external-auditing', 'accounting',
'External Audit Services',
'خدمات التدقيق الخارجي',
'Professional external audit for financial statement assurance',
'التدقيق الخارجي الاحترافي لتأكيد البيانات المالية',
'Get independent assurance of your financial statements through our external audit services. Our certified auditors provide credibility to your financial reporting and help you meet statutory and regulatory requirements.',
'احصل على تأكيد مستقل لبياناتك المالية من خلال خدمات التدقيق الخارجي لدينا. يوفر مدققونا المعتمدون المصداقية لتقاريرك المالية ويساعدك على تلبية المتطلبات القانونية والتنظيمية.',
'[{"title_en":"Financial Statement Audit","title_ar":"تدقيق البيانات المالية","description_en":"Independent verification of financials","description_ar":"التحقق المستقل من البيانات المالية"},{"title_en":"Compliance Testing","title_ar":"اختبار الامتثال","description_en":"Verify regulatory compliance","description_ar":"التحقق من الامتثال التنظيمي"},{"title_en":"Audit Report","title_ar":"تقرير التدقيق","description_en":"Auditor''s opinion on financial statements","description_ar":"رأي المدقق حول البيانات المالية"},{"title_en":"Management Letter","title_ar":"خطاب الإدارة","description_en":"Recommendations for improvements","description_ar":"توصيات للتحسينات"}]',
'[{"step":1,"title_en":"Audit Planning","title_ar":"تخطيط التدقيق","description_en":"Assess risk and scope","description_ar":"تقييم المخاطر والنطاق"},{"step":2,"title_en":"Fieldwork","title_ar":"العمل الميداني","description_en":"Conduct audit procedures","description_ar":"إجراء إجراءات التدقيق"},{"step":3,"title_en":"Review","title_ar":"المراجعة","description_en":"Review findings with management","description_ar":"مراجعة النتائج مع الإدارة"},{"step":4,"title_en":"Audit Report","title_ar":"تقرير التدقيق","description_en":"Issue auditor opinion and report","description_ar":"إصدار رأي المدقق والتقرير"}]',
'[{"name":"Financial Statements","name_ar":"البيانات المالية"},{"name":"Supporting Documents","name_ar":"الوثائق الداعمة"},{"name":"Internal Controls Assessment","name_ar":"تقييم الضوابط الداخلية"}]',
'[{"question_en":"Is external audit mandatory in UAE?","question_ar":"هل التدقيق الخارجي إلزامي في الإمارات؟","answer_en":"Yes, most companies must have external audit per UAE Commercial Companies Law","answer_ar":"نعم، معظم الشركات يجب أن تخضع للتدقيق الخارجي وفقاً لقانون الشركات التجارية الإماراتي"}]',
'checkmark',
7, TRUE, NOW(), NOW()),

('statutory-auditing', 'accounting',
'Statutory Audit',
'التدقيق القانوني',
'Compliance audit for statutory requirements',
'تدقيق الامتثال لمتطلبات قانونية',
'Meet all statutory audit requirements with our specialized statutory audit services. We ensure compliance with UAE commercial law and regulatory requirements while providing quality assurance of financial records.',
'الوفاء بجميع متطلبات التدقيق القانوني مع خدمات التدقيق القانوني المتخصصة لدينا. نضمن الامتثال لقانون التجارة الإماراتي والمتطلبات التنظيمية مع توفير ضمان الجودة للسجلات المالية.',
'[{"title_en":"Regulatory Compliance","title_ar":"الامتثال التنظيمي","description_en":"Ensure legal requirements met","description_ar":"التأكد من استيفاء المتطلبات القانونية"},{"title_en":"Statutory Report","title_ar":"التقرير القانوني","description_en":"Issue compliance audit opinion","description_ar":"إصدار رأي تدقيق الامتثال"},{"title_en":"Documentation","title_ar":"التوثيق","description_en":"Maintain audit documentation","description_ar":"الحفاظ على التوثيق الخاص بالتدقيق"}]',
'[{"step":1,"title_en":"Planning","title_ar":"التخطيط","description_en":"Identify statutory requirements","description_ar":"تحديد المتطلبات القانونية"},{"step":2,"title_en":"Audit Work","title_ar":"عمل التدقيق","description_en":"Perform audit procedures","description_ar":"إجراء عمل التدقيق"},{"step":3,"title_en":"Reporting","title_ar":"الإبلاغ","description_en":"Report audit findings","description_ar":"الإبلاغ عن نتائج التدقيق"}]',
'[{"name":"Financial Statements","name_ar":"البيانات المالية"},{"name":"Board Minutes","name_ar":"محاضر اجتماعات مجلس الإدارة"},{"name":"Regulatory Documents","name_ar":"الوثائق التنظيمية"}]',
'[{"question_en":"What does statutory audit cover?","question_ar":"ما الذي يغطيه التدقيق القانوني؟","answer_en":"Statutory audit covers verification of financial statements per legal requirements and standards","answer_ar":"يغطي التدقيق القانوني التحقق من البيانات المالية وفقاً للمتطلبات والمعايير القانونية"}]',
'certificate',
8, TRUE, NOW(), NOW()),

('vat-auditing', 'accounting',
'VAT Audit Services',
'خدمات تدقيق ضريبة القيمة المضافة',
'Specialized VAT compliance and audit support',
'دعم الامتثال والتدقيق المتخصص في ضريبة القيمة المضافة',
'Prepare for VAT audits with confidence. Our VAT audit specialists help you maintain compliant records, respond to FTA inquiries, and defend your VAT position during audits.',
'استعد لتدقيق ضريبة القيمة المضافة بثقة. يساعدك متخصصو تدقيق ضريبة القيمة المضافة لدينا على الحفاظ على السجلات المتوافقة والرد على استفسارات FTA والدفاع عن موقفك في ضريبة القيمة المضافة أثناء التدقيق.',
'[{"title_en":"VAT Record Review","title_ar":"مراجعة سجلات ضريبة القيمة المضافة","description_en":"Audit VAT documentation","description_ar":"تدقيق وثائق ضريبة القيمة المضافة"},{"title_en":"Audit Defense","title_ar":"الدفاع عن التدقيق","description_en":"Represent you with FTA","description_ar":"تمثيلك أمام سلطة الضرائب الفيدرالية"},{"title_en":"Remediation","title_ar":"المعالجة","description_en":"Correct audit findings","description_ar":"تصحيح نتائج التدقيق"}]',
'[{"step":1,"title_en":"Documentation Review","title_ar":"مراجعة التوثيق","description_en":"Review VAT records and filings","description_ar":"مراجعة سجلات ضريبة القيمة المضافة والإقرارات"},{"step":2,"title_en":"Gap Analysis","title_ar":"تحليل الفجوات","description_en":"Identify compliance gaps","description_ar":"تحديد فجوات الامتثال"},{"step":3,"title_en":"Audit Preparation","title_ar":"تحضير التدقيق","description_en":"Prepare audit responses","description_ar":"تحضير ردود التدقيق"},{"step":4,"title_en":"Representation","title_ar":"التمثيل","description_en":"Support during FTA audit","description_ar":"الدعم أثناء تدقيق سلطة الضرائب الفيدرالية"}]',
'[{"name":"VAT Returns","name_ar":"إقرارات ضريبة القيمة المضافة"},{"name":"Supporting Invoices","name_ar":"الفواتير الداعمة"},{"name":"Credit Note Records","name_ar":"سجلات إشعارات الخصم"}]',
'[{"question_en":"What happens during a VAT audit?","question_ar":"ماذا يحدث أثناء تدقيق ضريبة القيمة المضافة؟","answer_en":"FTA reviews your VAT records, invoices, and payments to verify compliance","answer_ar":"تراجع سلطة الضرائب الفيدرالية سجلات ضريبة القيمة المضافة والفواتير والدفعات للتحقق من الامتثال"}]',
'search',
9, TRUE, NOW(), NOW()),

('corporate-tax-auditing', 'accounting',
'Corporate Tax Audit',
'تدقيق ضريبة دخل الشركات',
'Expert representation during corporate tax audits',
'التمثيل الخبير أثناء تدقيق ضريبة دخل الشركات',
'Navigate corporate tax audits with our experienced team. We help prepare audit responses, represent you before tax authorities, and resolve tax disputes efficiently.',
'تنقل تدقيق ضريبة دخل الشركات مع فريقنا ذي الخبرة. نساعدك على تحضير ردود التدقيق والتمثيل أمام السلطات الضريبية وحل نزاعات الضرائب بكفاءة.',
'[{"title_en":"Audit Response","title_ar":"رد التدقيق","description_en":"Prepare detailed audit responses","description_ar":"تحضير ردود التدقيق المفصلة"},{"title_en":"Tax Authority Representation","title_ar":"تمثيل السلطات الضريبية","description_en":"Represent before FTA","description_ar":"التمثيل أمام سلطة الضرائب الفيدرالية"},{"title_en":"Dispute Resolution","title_ar":"حل النزاعات","description_en":"Handle tax appeals","description_ar":"التعامل مع استئنافات الضرائب"}]',
'[{"step":1,"title_en":"Audit Notification","title_ar":"إخطار التدقيق","description_en":"Analyze FTA audit notice","description_ar":"تحليل إخطار تدقيق سلطة الضرائب الفيدرالية"},{"step":2,"title_en":"Documentation Gathering","title_ar":"جمع التوثيق","description_en":"Collect supporting documents","description_ar":"جمع الوثائق الداعمة"},{"step":3,"title_en":"Response Preparation","title_ar":"تحضير الرد","description_en":"Develop comprehensive response","description_ar":"تطوير رد شامل"},{"step":4,"title_en":"Authority Meetings","title_ar":"اجتماعات السلطات","description_en":"Attend meetings with FTA","description_ar":"حضور اجتماعات مع سلطة الضرائب الفيدرالية"}]',
'[{"name":"Audit Notice","name_ar":"إخطار التدقيق"},{"name":"Financial Documents","name_ar":"الوثائق المالية"},{"name":"Prior Correspondence","name_ar":"المراسلة السابقة"}]',
'[{"question_en":"How long does a tax audit typically take?","question_ar":"كم من الوقت يستغرق تدقيق الضريبة عادة؟","answer_en":"Corporate tax audits typically take 6-12 months depending on complexity","answer_ar":"يستغرق تدقيق ضريبة دخل الشركات عادة 6-12 شهراً حسب التعقيد"}]',
'clipboard',
10, TRUE, NOW(), NOW()),

('forensic-auditing', 'accounting',
'Forensic Audit & Investigations',
'التدقيق الجنائي والتحقيقات',
'Specialized forensic audit and fraud investigation services',
'خدمات التدقيق الجنائي والتحقيقات في الاحتيال المتخصصة',
'Detect and investigate financial fraud, embezzlement, and irregularities. Our forensic specialists use advanced techniques to uncover fraud and support litigation.',
'كشف والتحقيق في الاحتيال المالي والاختلاس والمخالفات. يستخدم متخصصو التدقيق الجنائي لدينا تقنيات متقدمة للكشف عن الاحتيال ودعم الدعاوى القضائية.',
'[{"title_en":"Fraud Investigation","title_ar":"التحقيق في الاحتيال","description_en":"Investigate suspected fraud","description_ar":"التحقيق في الاحتيال المشبوه"},{"title_en":"Evidence Gathering","title_ar":"جمع الأدلة","description_en":"Collect and preserve evidence","description_ar":"جمع والحفاظ على الأدلة"},{"title_en":"Litigation Support","title_ar":"دعم الدعاوى القضائية","description_en":"Expert witness services","description_ar":"خدمات الشاهد الخبير"}]',
'[{"step":1,"title_en":"Investigation Planning","title_ar":"تخطيط التحقيق","description_en":"Define scope and objectives","description_ar":"تحديد النطاق والأهداف"},{"step":2,"title_en":"Data Analysis","title_ar":"تحليل البيانات","description_en":"Analyze financial data for anomalies","description_ar":"تحليل البيانات المالية للشذوذ"},{"step":3,"title_en":"Interview & Evidence","title_ar":"المقابلة والأدلة","description_en":"Conduct interviews and gather evidence","description_ar":"إجراء مقابلات وجمع الأدلة"},{"step":4,"title_en":"Report","title_ar":"التقرير","description_en":"Issue forensic audit report","description_ar":"إصدار تقرير التدقيق الجنائي"}]',
'[{"name":"Financial Records","name_ar":"السجلات المالية"},{"name":"Transaction Data","name_ar":"بيانات المعاملات"},{"name":"Communication Records","name_ar":"سجلات الاتصالات"}]',
'[{"question_en":"What is a forensic audit?","question_ar":"ما هو التدقيق الجنائي؟","answer_en":"A forensic audit investigates financial irregularities and potential fraud using specialized techniques","answer_ar":"يحقق التدقيق الجنائي في المخالفات المالية والاحتيال المحتمل باستخدام تقنيات متخصصة"}]',
'magnifier',
11, TRUE, NOW(), NOW());

-- Corporate Services - Corporate Category
INSERT INTO services (slug, category, name_en, name_ar, description_en, description_ar, long_description_en, long_description_ar, features, flow_steps, documents, faqs, icon, sort_order, is_active, created_at, updated_at) VALUES

('company-registration', 'corporate',
'Company Registration & Formation',
'تسجيل وتشكيل الشركات',
'Full company registration services from formation to compliance',
'خدمات تسجيل الشركات الكاملة من التأسيس إلى الامتثال',
'Start your business in UAE seamlessly. We handle complete company registration including business licensing, trade name registration, and initial compliance setup. Whether youre establishing a new venture in Dubai, Abu Dhabi, or any free zone, we guide you through every step.',
'ابدأ عملك في الإمارات بسلاسة. نتعامل مع تسجيل الشركات الكامل بما في ذلك ترخيص الأعمال وتسجيل اسم التجارة والإعداد الأولي للامتثال. سواء كنت تؤسس مشروعاً جديداً في دبي أو أبو ظبي أو أي منطقة حرة، فإننا نرشدك خلال كل خطوة.',
'[{"title_en":"Business License","title_ar":"رخصة العمل","description_en":"Obtain your business license","description_ar":"الحصول على رخصة عملك"},{"title_en":"Trade Name","title_ar":"اسم التجارة","description_en":"Register business trade name","description_ar":"تسجيل اسم التجارة للعمل"},{"title_en":"Legal Structure","title_ar":"الهيكل القانوني","description_en":"Set up appropriate legal entity","description_ar":"إنشاء كيان قانوني مناسب"},{"title_en":"Initial Compliance","title_ar":"الامتثال الأولي","description_en":"Register for VAT, labor, social insurance","description_ar":"التسجيل لضريبة القيمة المضافة والعمل والضمان الاجتماعي"}]',
'[{"step":1,"title_en":"Consultation","title_ar":"الاستشارة","description_en":"Discuss business structure and location","description_ar":"مناقشة هيكل العمل والموقع"},{"step":2,"title_en":"Documentation","title_ar":"التوثيق","description_en":"Prepare required documents","description_ar":"تحضير الوثائق المطلوبة"},{"step":3,"title_en":"Submission","title_ar":"التقديم","description_en":"Submit to authorities","description_ar":"الرفع للسلطات"},{"step":4,"title_en":"License Issuance","title_ar":"إصدار الرخصة","description_en":"Obtain business license","description_ar":"الحصول على رخصة العمل"}]',
'[{"name":"Passport Copy","name_ar":"صورة جواز السفر"},{"name":"Visa Copy","name_ar":"صورة التأشيرة"},{"name":"Address Proof","name_ar":"إثبات العنوان"},{"name":"NOC from Employer","name_ar":"موافقة صاحب العمل"}]',
'[{"question_en":"How long does company registration take?","question_ar":"كم من الوقت يستغرق تسجيل الشركة؟","answer_en":"Standard registration typically takes 2-4 weeks depending on entity type and jurisdiction","answer_ar":"يستغرق التسجيل القياسي عادة 2-4 أسابيع حسب نوع الكيان والقطاع القضائي"},{"question_en":"What business structures are available?","question_ar":"ما هي هياكل الأعمال المتاحة؟","answer_en":"You can establish an LLC, L.L.C in free zones, partnership, or branch office","answer_ar":"يمكنك إنشاء شركة ذات مسؤولية محدودة أو شراكة أو فرع مكتب"}]',
'building',
12, TRUE, NOW(), NOW()),

('trademark-registration', 'corporate',
'Trademark & IP Registration',
'تسجيل العلامات التجارية والملكية الفكرية',
'Protect your intellectual property with trademark and IP registration',
'حماية ملكيتك الفكرية من خلال تسجيل العلامات التجارية والملكية الفكرية',
'Secure your brand and intellectual property rights in UAE. We handle trademark registration, copyright protection, and other IP matters to ensure your business assets are legally protected.',
'ضمان حقوق علامتك التجارية والملكية الفكرية في الإمارات. نتعامل مع تسجيل العلامات التجارية وحماية حقوق النشر وغيرها من مسائل الملكية الفكرية لضمان حماية أصول عملك قانوناً.',
'[{"title_en":"Trademark Search","title_ar":"البحث عن العلامات التجارية","description_en":"Check availability of trademark","description_ar":"التحقق من توفر العلامة التجارية"},{"title_en":"Registration","title_ar":"التسجيل","description_en":"File trademark registration","description_ar":"تقديم تطبيق تسجيل العلامة التجارية"},{"title_en":"Copyright Protection","title_ar":"حماية حقوق النشر","description_en":"Protect creative works","description_ar":"حماية الأعمال الإبداعية"},{"title_en":"IP Enforcement","title_ar":"إنفاذ الملكية الفكرية","description_en":"Enforce intellectual property rights","description_ar":"إنفاذ حقوق الملكية الفكرية"}]',
'[{"step":1,"title_en":"Trademark Search","title_ar":"البحث عن العلامات التجارية","description_en":"Conduct availability search","description_ar":"إجراء بحث التوفر"},{"step":2,"title_en":"Application Preparation","title_ar":"تحضير الطلب","description_en":"Prepare registration application","description_ar":"تحضير طلب التسجيل"},{"step":3,"title_en":"Filing","title_ar":"التقديم","description_en":"Submit to trade mark office","description_ar":"التقديم لمكتب العلامات التجارية"},{"step":4,"title_en":"Approval","title_ar":"الموافقة","description_en":"Obtain registration certificate","description_ar":"الحصول على شهادة التسجيل"}]',
'[{"name":"Logo/Design","name_ar":"شعار/التصميم"},{"name":"Business Details","name_ar":"تفاصيل العمل"},{"name":"ID Copy","name_ar":"صورة الهوية"}]',
'[{"question_en":"How long is trademark registration valid?","question_ar":"كم مدة صلاحية تسجيل العلامة التجارية؟","answer_en":"Trademark registration is valid for 10 years and can be renewed indefinitely","answer_ar":"تسجيل العلامة التجارية صالح لمدة 10 سنوات ويمكن تجديده بلا حدود"}]',
'lightbulb',
13, TRUE, NOW(), NOW()),

('business-bank-account', 'corporate',
'Business Bank Account Setup',
'إعداد حساب بنك الأعمال',
'Facilitate business bank account opening with major UAE banks',
'تسهيل فتح حسابات الأعمال البنكية مع البنوك الرئيسية في الإمارات',
'Streamline your banking setup. We assist with opening business bank accounts at UAE banks, providing compliance documentation and liaising with financial institutions.',
'تبسيط إعداد البنك لديك. نساعد في فتح حسابات الأعمال البنكية في بنوك الإمارات، وتوفير وثائق الامتثال والتواصل مع المؤسسات المالية.',
'[{"title_en":"Bank Selection","title_ar":"اختيار البنك","description_en":"Identify suitable bank for your needs","description_ar":"تحديد البنك المناسب لاحتياجاتك"},{"title_en":"Documentation","title_ar":"التوثيق","description_en":"Prepare bank documents","description_ar":"تحضير وثائق البنك"},{"title_en":"Application","title_ar":"الطلب","description_en":"Submit account opening application","description_ar":"تقديم طلب فتح الحساب"},{"title_en":"Account Activation","title_ar":"تفعيل الحساب","description_en":"Activate business account","description_ar":"تفعيل حساب الأعمال"}]',
'[{"step":1,"title_en":"Consultation","title_ar":"الاستشارة","description_en":"Discuss banking needs","description_ar":"مناقشة احتياجاتك البنكية"},{"step":2,"title_en":"Document Preparation","title_ar":"تحضير الوثائق","description_en":"Collect required documents","description_ar":"جمع الوثائق المطلوبة"},{"step":3,"title_en":"Bank Meetings","title_ar":"اجتماعات البنك","description_en":"Arrange bank meetings","description_ar":"ترتيب اجتماعات البنك"},{"step":4,"title_en":"Account Opening","title_ar":"فتح الحساب","description_en":"Complete account opening process","description_ar":"استكمال عملية فتح الحساب"}]',
'[{"name":"Commercial License","name_ar":"الرخصة التجارية"},{"name":"Memorandum of Association","name_ar":"عقد التأسيس"},{"name":"ID & Passport","name_ar":"الهوية وجواز السفر"},{"name":"Address Proof","name_ar":"إثبات العنوان"}]',
'[{"question_en":"What documents are needed for bank account opening?","question_ar":"ما هي الوثائق المطلوبة لفتح حساب بنكي؟","answer_en":"Typically commercial license, passport, visa, address proof, and financial statements","answer_ar":"عادة رخصة تجارية وجواز سفر وتأشيرة وإثبات عنوان وبيانات مالية"}]',
'credit-card',
14, TRUE, NOW(), NOW()),

('pro-services', 'corporate',
'PRO Services',
'خدمات الممثل القانوني',
'Complete PRO (Public Relations Officer) services for corporate matters',
'خدمات الممثل القانوني الكاملة لشؤون الشركات',
'Streamline your government interactions. Our PRO services handle visa processing, labour approvals, document attestation, and other government liaisons.',
'بسّط تفاعلك مع الحكومة. تتعامل خدمات الممثل القانوني لدينا مع معالجة التأشيرات والموافقات العمالية وتصديق الوثائق والتواصل الحكومي الآخر.',
'[{"title_en":"Visa Processing","title_ar":"معالجة التأشيرات","description_en":"Handle employee visa applications","description_ar":"التعامل مع طلبات تأشيرات الموظفين"},{"title_en":"Labour Approvals","title_ar":"الموافقات العمالية","description_en":"Obtain labour approvals and permits","description_ar":"الحصول على الموافقات والرخص العمالية"},{"title_en":"Document Attestation","title_ar":"تصديق الوثائق","description_en":"Attest and verify documents","description_ar":"تصديق والتحقق من الوثائق"},{"title_en":"Government Liaison","title_ar":"الاتصال الحكومي","description_en":"Handle government communications","description_ar":"التعامل مع الاتصالات الحكومية"}]',
'[{"step":1,"title_en":"Request Submission","title_ar":"تقديم الطلب","description_en":"Submit PRO service request","description_ar":"تقديم طلب خدمة الممثل القانوني"},{"step":2,"title_en":"Document Collection","title_ar":"جمع الوثائق","description_en":"Gather required documents","description_ar":"جمع الوثائق المطلوبة"},{"step":3,"title_en":"Government Processing","title_ar":"معالجة حكومية","description_en":"Process with government agencies","description_ar":"المعالجة مع الوكالات الحكومية"},{"step":4,"title_en":"Delivery","title_ar":"التسليم","description_en":"Deliver completed applications","description_ar":"تسليم الطلبات المكتملة"}]',
'[{"name":"Passport","name_ar":"جواز السفر"},{"name":"Employment Offer","name_ar":"عرض العمل"},{"name":"Medical Reports","name_ar":"التقارير الطبية"},{"name":"Educational Certificates","name_ar":"شهادات تعليمية"}]',
'[{"question_en":"How long does visa processing take?","question_ar":"كم من الوقت تستغرق معالجة التأشيرة؟","answer_en":"Employee visas typically process in 15-30 days depending on nationality","answer_ar":"تتم معالجة تأشيرات الموظفين عادة في 15-30 يوماً حسب الجنسية"}]',
'users',
15, TRUE, NOW(), NOW()),

('golden-visa', 'corporate',
'Golden Visa & Sponsorship',
'التأشيرة الذهبية والكفالة',
'Support for Golden Visa and residency sponsorship applications',
'الدعم لتطبيقات التأشيرة الذهبية والكفالة السكنية',
'Apply for UAE Golden Visa with expert guidance. We assist with sponsorship requirements, documentation, and application processing to secure long-term residency.',
'تقدم بطلب للتأشيرة الذهبية في الإمارات بإرشادات خبيرة. نساعد في متطلبات الكفالة والتوثيق ومعالجة الطلبات لتأمين الإقامة طويلة الأجل.',
'[{"title_en":"Golden Visa Application","title_ar":"تطبيق التأشيرة الذهبية","description_en":"Guide Golden Visa process","description_ar":"إرشاد عملية التأشيرة الذهبية"},{"title_en":"Documentation","title_ar":"التوثيق","description_en":"Prepare required documentation","description_ar":"تحضير التوثيق المطلوب"},{"title_en":"Sponsorship Setup","title_ar":"إعداد الكفالة","description_en":"Arrange visa sponsorship","description_ar":"ترتيب كفالة التأشيرة"},{"title_en":"Family Support","title_ar":"دعم العائلة","description_en":"Include family members","description_ar":"إدراج أفراد العائلة"}]',
'[{"step":1,"title_en":"Eligibility Review","title_ar":"مراجعة الأهلية","description_en":"Determine Golden Visa eligibility","description_ar":"تحديد أهلية التأشيرة الذهبية"},{"step":2,"title_en":"Application Preparation","title_ar":"تحضير الطلب","description_en":"Prepare visa application","description_ar":"تحضير طلب التأشيرة"},{"step":3,"title_en":"Submission","title_ar":"التقديم","description_en":"Submit to immigration","description_ar":"التقديم للهجرة"},{"step":4,"title_en":"Processing","title_ar":"المعالجة","description_en":"Monitor application status","description_ar":"مراقبة حالة الطلب"}]',
'[{"name":"Passport","name_ar":"جواز السفر"},{"name":"Bank Statements","name_ar":"كشوف الحسابات البنكية"},{"name":"Investment Proof","name_ar":"إثبات الاستثمار"},{"name":"Medical Reports","name_ar":"التقارير الطبية"}]',
'[{"question_en":"Who is eligible for Golden Visa?","question_ar":"من هو مؤهل للتأشيرة الذهبية؟","answer_en":"Investors, specialized talents, and entrepreneurs meeting specific criteria are eligible","answer_ar":"المستثمرون والمواهب المتخصصة ورجال الأعمال الذين يستوفون معايير محددة مؤهلون"}]',
'star',
16, TRUE, NOW(), NOW()),

('company-reconstruction', 'corporate',
'Company Reconstruction & Restructuring',
'إعادة بناء الشركات وإعادة الهيكلة',
'Business restructuring and company reconstruction services',
'خدمات إعادة هيكلة الأعمال وإعادة بناء الشركات',
'Navigate company changes seamlessly. Our restructuring services handle mergers, acquisitions, liquidation, and business restructuring with full legal and regulatory support.',
'تنقل تغييرات الشركات بسلاسة. تتعامل خدمات إعادة الهيكلة لدينا مع الدمج والاستحواذ والتصفية وإعادة هيكلة الأعمال مع الدعم القانوني والتنظيمي الكامل.',
'[{"title_en":"Merger & Acquisition","title_ar":"الدمج والاستحواذ","description_en":"Facilitate M&A transactions","description_ar":"تسهيل معاملات الدمج والاستحواذ"},{"title_en":"Restructuring Planning","title_ar":"تخطيط إعادة الهيكلة","description_en":"Develop restructuring strategy","description_ar":"تطوير استراتيجية إعادة الهيكلة"},{"title_en":"Legal Documentation","title_ar":"التوثيق القانوني","description_en":"Prepare all legal documents","description_ar":"تحضير جميع الوثائق القانونية"},{"title_en":"Regulatory Filings","title_ar":"الإيداعات التنظيمية","description_en":"Handle regulatory submissions","description_ar":"التعامل مع الإيداعات التنظيمية"}]',
'[{"step":1,"title_en":"Restructuring Analysis","title_ar":"تحليل إعادة الهيكلة","description_en":"Analyze restructuring needs","description_ar":"تحليل احتياجات إعادة الهيكلة"},{"step":2,"title_en":"Planning","title_ar":"التخطيط","description_en":"Develop restructuring plan","description_ar":"تطوير خطة إعادة الهيكلة"},{"step":3,"title_en":"Implementation","title_ar":"التنفيذ","description_en":"Execute restructuring steps","description_ar":"تنفيذ خطوات إعادة الهيكلة"},{"step":4,"title_en":"Compliance","title_ar":"الامتثال","description_en":"Ensure regulatory compliance","description_ar":"ضمان الامتثال التنظيمي"}]',
'[{"name":"Financial Statements","name_ar":"البيانات المالية"},{"name":"Board Resolutions","name_ar":"قرارات مجلس الإدارة"},{"name":"Shareholder Approvals","name_ar":"موافقات المساهمين"},{"name":"Legal Structure Documents","name_ar":"وثائق الهيكل القانوني"}]',
'[{"question_en":"What is involved in company restructuring?","question_ar":"ما الذي ينطوي على إعادة هيكلة الشركة؟","answer_en":"Restructuring can involve ownership changes, legal entity changes, or operational reorganization","answer_ar":"قد تتضمن إعادة الهيكلة تغييرات الملكية أو تغييرات الكيان القانوني أو إعادة تنظيم التشغيل"}]',
'arrow-right-circle',
17, TRUE, NOW(), NOW());

-- Seed testimonials table
INSERT INTO testimonials (name, title, company, quote_en, quote_ar, rating, is_active, sort_order, created_at) VALUES

('Fatima Al-Suwaidi', 'Finance Director', 'AltimaCare LLC',
'Sage Advisory successfully navigated our complex VAT audit with the FTA. Their expertise and attention to detail saved us significant time and stress. Highly recommended!',
'تنقلت Sage Advisory بنجاح من خلال تدقيق ضريبة القيمة المضافة المعقد لدينا مع سلطة الضرائب الفيدرالية. أدت خبرتهم واهتمامهم بالتفاصيل إلى توفير وقت وضغط كبير. موصى به بشدة!',
5, TRUE, 1, NOW()),

('Arjun Mehta', 'Founder', 'Tectonic DMCC',
'We have been working with Sage for our accounting and audit needs for the past 3 years. Their team is professional, responsive, and understands our business. Great value for money.',
'كنا نعمل مع Sage لاحتياجات المحاسبة والتدقيق لدينا في السنوات الثلاث الماضية. فريقهم احترافي وسريع الاستجابة ويفهم عملنا. قيمة ممتازة مقابل المال.',
5, TRUE, 2, NOW()),

('Lina Haddad', 'Partner', 'Vida Interiors',
'The Sage team made our Golden Visa process straightforward and stress-free. From sponsorship to final approvals, they handled everything professionally. Wonderful experience!',
'جعل فريق Sage عملية التأشيرة الذهبية الخاصة بنا مباشرة وخالية من التوتر. من الكفالة إلى الموافقات النهائية، تعاملوا مع كل شيء بشكل احترافي. تجربة رائعة!',
5, TRUE, 3, NOW());

-- Seed FAQs table
INSERT INTO faqs (question_en, question_ar, answer_en, answer_ar, category, sort_order, is_active, created_at) VALUES

('What is the UAE corporate tax rate?', 'ما هو معدل ضريبة دخل الشركات في الإمارات؟',
'The UAE does not levy corporate income tax on most businesses. However, certain sectors like oil and gas, and foreign companies in free zones are subject to 0% to various rates depending on circumstances.',
'لا تفرض الإمارات ضريبة دخل على معظم الشركات. ومع ذلك، تخضع القطاعات معينة مثل النفط والغاز والشركات الأجنبية في المناطق الحرة لمعدلات من 0% إلى معدلات مختلفة حسب الظروف.',
'tax', 1, TRUE, NOW()),

('Do I need to register for VAT if my turnover is below the threshold?', 'هل أحتاج إلى التسجيل لضريبة القيمة المضافة إذا كان دخلي أقل من الحد؟',
'Registration is mandatory if your annual turnover exceeds AED 375,000. If below this threshold, registration is optional but can be advantageous for input VAT recovery.',
'التسجيل إلزامي إذا تجاوز دخلك السنوي 375 ألف درهم. إذا كان أقل من هذا الحد، فإن التسجيل اختياري لكن يمكن أن يكون مفيداً لاسترجاع ضريبة المدخلات.',
'tax', 2, TRUE, NOW()),

('What records must I maintain for FTA compliance?', 'ما السجلات التي يجب أن أحتفظ بها للامتثال لـ FTA؟',
'You must maintain invoices, receipts, bank statements, expense documentation, payroll records, and VAT return copies for minimum 5 years. All records must be in Arabic and English.',
'يجب عليك الاحتفاظ بالفواتير والإيصالات وكشوف الحسابات البنكية وتوثيق النفقات وسجلات الرواتب ونسخ إقرارات ضريبة القيمة المضافة لمدة 5 سنوات على الأقل. يجب أن تكون جميع السجلات باللغة العربية والإنجليزية.',
'tax', 3, TRUE, NOW()),

('How can Sage help with a tax audit?', 'كيف يمكن لـ Sage أن تساعد في تدقيق الضرائب؟',
'We provide complete audit support including document preparation, responding to FTA inquiries, representing you in meetings, and defending your tax position. We work to minimize adjustments and resolve disputes efficiently.',
'نوفر دعم تدقيق شامل بما في ذلك تحضير الوثائق والرد على استفسارات سلطة الضرائب الفيدرالية والتمثيل في الاجتماعات والدفاع عن موقفك الضريبي. نعمل على تقليل التعديلات وحل النزاعات بكفاءة.',
'tax', 4, TRUE, NOW()),

('Do free zone companies have to pay corporate tax?', 'هل شركات المناطق الحرة مضطرة لدفع ضريبة دخل الشركات؟',
'Most free zone companies are exempt from corporate income tax. However, they must still comply with VAT registration if turnover exceeds thresholds and must maintain proper accounting records.',
'معظم شركات المناطق الحرة معفاة من ضريبة دخل الشركات. ومع ذلك، يجب عليهم الامتثال لتسجيل ضريبة القيمة المضافة إذا تجاوز الدخل الحدود والحفاظ على سجلات محاسبية مناسبة.',
'tax', 5, TRUE, NOW());
